### ISSUE TITLE
Blob Storage API

### ISSUE THREAD

**Issue by li1** [JuliaComputing/Azure.jl#15]
Hi all,

Thanks for the call with @nhdaly today and sorry that I couldn't join! Maybe we can make it work next week. 🤗 

Nathan mentioned that you used `Swagger.jl` to generate the Azure API from a https://github.com/Azure/azure-rest-api-specs fork and that we might also be able to generate similar APIs for Blob access that way.

We actually investigated this yesterday, and also successfully generated some APIs using Swagger. Unfortunately, we discovered that parts of the [BlobService API](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api) seem to be missing in the microsoft repo — in particular APIs for `put`ting and `get`ting blobs, while `BlobContainers` seem to exist (*). We also assumed that this is the reason why you provided the separate `deleteBlob` API & REST auth in the repo.

Do you have an idea on whether we can source the specs from somewhere else? Perhaps we've also overlooked something? Otherwise, I can also look into creating an upstream issue on the microsoft spec repo, however their turnaround time appears to be volatile.

Cheers!

(*) There also exists a [blob spec](https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json) in the `storage-dataplane-preview` branch, but that sits under the `DataLakeStorage`, so not sure if it is applicable to the `BlobStorage`.

**Comment by tanmaykm** [comment]
The [blob spec](https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json) does seem to address that. It will be good to use that once it is released.

The REST API protocol is implemented in [rest_api_protocol.jl](https://github.com/JuliaComputing/Azure.jl/blob/master/src/rest_api_protocol.jl). Azure.jl now has only the [`deleteBlob` implemeted](https://github.com/JuliaComputing/Azure.jl/blob/master/src/Storage/StorageServices/blob.jl). Other APIs can be added along the same lines.

Is there a subset of the APIs that's needed immediately? Maybe implementing those first will make this useful earlier.

**Comment by tanmaykm** [comment]
Some more of the commonly used Blob Storage APIs are now added with #17

**Comment by li1** [comment]
Hi @tanmaykm, thanks for adding this!

I saw the changes to `rest_api_protocol`, and I'm wondering whether there's any way of passing kebab-cased headers to https://github.com/JuliaComputing/Azure.jl/blob/master/src/rest_api_protocol.jl#L48-L68. This is necessary for providing further `x-ms-...`-headers, e.g. `x-ms-blob-type` (required for blob `PUT`s), or for custom metadata.

Currently, it uses a `; headers...` function argument to convert from passed `kwargs`, but I don't know how to formulate a valid `kwarg` with `-` in Julia.

Best!

**Comment by li1** [comment]
Nathan told me about the `var””` macro. Crazy stuff! So I’m closing here for now. Thanks again <3

**Comment by NHDaly** [comment]
Still, just want to note that this passing `(;var"x-ms-blob-type" = "...") is pretty esoteric, and presumably most users wouldn't think of this. It might make sense to also have a dictionary-based API so that you could pass these strings directly?

**Comment by NHDaly** [comment]
and/or call out using `var""` as an option in the doc-string?

**Comment by tanmaykm** [comment]
Yes, may be instead of [this](https://github.com/JuliaComputing/Azure.jl/blob/869c880efb7db3d7fbdcccab85c948c5979437ff/src/rest_api_protocol.jl#L48) something like 
`ServiceRequest(account, verb, resource; data=nothing, headers=nothing)` will be better.

**Comment by NHDaly** [comment]
Seems reasonable to me!

**Comment by tanmaykm** [comment]
Just curious, are you having to use `ServiceRequest` directly instead of the APIs added in #17 because certain API that you need is missing? Then it may be better to implement that.

**Comment by li1** [comment]
Hi @tanmaykm, we're currently using `ServiceRequest` because we don't want to use a service principal but rather a managed identity in the future. As far as I understand, the API doesn't support that?

**Comment by tanmaykm** [comment]
Yes, managed identities are not supported yet in Azure.jl. I have raised an issue now (https://github.com/JuliaComputing/Azure.jl/issues/19) with a possible approach for implementation.
